- name: Ensure git is installed
  apt:
    name: git
    state: present

- name: Clone repository
  git:
    repo: https://github.com/IgorChecinski/status-checker.git
    dest: /home/ubuntu/status-checker
    version: main
    force: yes

- name: Create .env file
  copy:
    dest: /home/ubuntu/status-checker/.env
    content: |
      DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
      REDIS_HOST=redis
      REDIS_PORT=6379
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=password
      POSTGRES_DB=mydatabase
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Stop running containers
  shell: docker-compose down
  args:
    chdir: /home/ubuntu/status-checker
  ignore_errors: yes

- name: Start containers
  shell: docker-compose up -d
  args:
    chdir: /home/ubuntu/status-checker
