name: Python CI/CD with Docker

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Set env vars for test
      run: |
        echo "DATABASE_URL=sqlite:///./test.db" >> $GITHUB_ENV
        echo "REDIS_HOST=localhost" >> $GITHUB_ENV
        echo "REDIS_PORT=6379" >> $GITHUB_ENV

    - name: Run tests with pytest
      run: |
        PYTHONPATH=. pytest

    - name: Build Docker image
      run: |
        docker build -t url-monitor .

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 url-monitor
        for i in {1..15}; do
          echo "Waiting for the app to be ready... ($i)"
          curl --fail http://localhost:8000 && break || sleep 2
        done

    - name: Clean up Docker containers
      run: |
        CONTAINERS=$(docker ps -q)
        if [ -n "$CONTAINERS" ]; then
          echo "Stopping containers..."
          docker stop $CONTAINERS
          docker rm $CONTAINERS
        else
          echo "No containers to stop."
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Save SSH private key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Create inventory for CI
      run: |
        echo "[vm]" > provisioning/inventory_ci.ini
        echo "34.145.16.230 ansible_user=ubuntu" >> provisioning/inventory_ci.ini

    - name: Mark repo directory as safe for git
      run: git config --global --add safe.directory /home/ubuntu/status-checker

    - name: Deploy to VM with Ansible
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: provisioning/deploy.yml
        inventory: provisioning/inventory_ci.ini
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'
        ANSIBLE_PRIVATE_KEY_FILE: private_key.pem
